function G = SwarmFitness(x, y, Y_demand_vector, ...
                             dj, uj1, uj2, uj3, ...
                             E1, E2, E3, E, ...
                             C1, C2, t, T, q)

    G = 1/ObjectiveFunction(x, y, Y_demand_vector, ...
                             dj, uj1, uj2, uj3, ...
                             E1, E2, E3, E, ...
                             C1, C2, t, T, q);

end